include theme.conf

# --- Estética y Transparencia ---
background_opacity 0.4
dynamic_background_opacity yes

# --- Fuentes ---
font_family      JetBrainsMono Nerd Font
font_size        11.0

# --- Ventana y Bordes ---
window_padding_width 10
confirm_os_window_close 0

# --- Cursor ---
cursor_shape beam
cursor_blink_interval 0.5

# --- Colores ---
# foreground #dddddd
# background #111111

# --- Cursor Avanzado ---
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval -1
cursor_trail 1
cursor_trail_decay 0.1 0.4

url_style curly
show_hyperlink_targets yes