##############
# ANIMATIONS #
##############

animations {
    enabled = yes, please :

    # Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1
    bezier = easePersonal,   0.65, 0.34, 0.46, 0.83
    bezier = partialLinear,  0.28, 0.51, 0.44, 0.66
    bezier = promontory,     0.2,  0.51, 0.64, 0.55
    bezier = notHill,        0.64, 0.11, 0.92, 0.47
    bezier = hill,           0.08, 0.51, 0.45, 0.92

    # Default animations, see https://wiki.hypr.land/Configuring/Animations/
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = global,        1,     2.73,  promontory

    ############
    ## LAYERS ##
    ############

    animation = layersIn,      1,     3.96,  easePersonal,  slide
    animation = layersOut,     1,     3.45,  partialLinear, slide
    animation = fadeLayersIn,  1,     2.79,  notHill
    animation = fadeLayersOut, 1,     2.39,  hill

    #############
    ## WINDOWS ##
    #############

    animation = windowsIn,     1,     2.45,  promontory
    animation = windowsOut,    1,     2.78,  promontory, slide
    animation = fadeIn,        1,     2.43,  almostLinear
    animation = fadeOut,       1,     1.46,  almostLinear    
    animation = border,        1,     4.49,  promontory
    
    ################
    ## WORKSPACES ##
    ################
    
    animation = workspacesIn,          1,     2.1,   easePersonal,  slide
    animation = workspacesOut,         1,     1.95,  easePersonal,  slide
    animation = specialWorkspaceIn,    1,     1.45,  partialLinear, slide bottom
    animation = specialWorkspaceOut,   1,     2.29,  easePersonal, slide top
    animation = zoomFactor,    1,     7,     quick
}