#################
### AUTOSTART ###
#################

#exec-once = nm-applet
exec-once = waybar
exec-once = hyprpaper -c ~/.config/hypr/hyprpaper.conf
exec-once = spotify --force-device-scale-factor=0.75
exec-once = /usr/lib/gnome-keyring/gnome-keyring-daemon --start --components=secrets
exec-once = gnome-keyring-daemon --start --components=secrets