wallpaper {
    monitor = eDP-1
    path = /home/johann/img/wallpaper/stormLight.jpg
    fit_mode = cover
}

# Fallback para cualquier monitor no especificado arriba
wallpaper {
    monitor = 
    path = /home/johann/img/wallpaper/stormLight.jpg
    fit_mode = cover
}

splash = false