layerrule {
    name = waybar-blur
    match:namespace = waybar
    
    blur = on
}

windowrule {
    name = spotify-float
    match:class = ^(spotify)$
    
    float = on
    size = 975 450
    move = 265 155
}

windowrule {
    name = volume-control
    match:class = ^(org.pulseaudio.pavucontrol)$
    
    float = on
    size = 436 277
    move = 837 42
}

windowrule {
    name = org.kde.dolphin-float
    match:class = ^(org.kde.dolphin)$
    
    float = on
    size = 650 450
    move = 570 230
}

windowrule {
    name = suppress-maximize-requests
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-dragging
    match:class = ^$
    match:title = ^$
    match:xwayland = 1
    match:float = 1
    match:fullscreen = 0
    match:pin = 0
    
    no_focus = on
}

windowrule {
    name = steam
    match:class = ^(steam)$
}

windowrule {
    name = steam-friends
    match:class = ^(steam)$
    match:title = ^(Friends List)
    float = on
    size = 225 450
    move = 1050 185
}

#######################
# Ventanas Emergentes #
#######################

windowrule {
    name = brave-popups
    match:class = ^(brave)$
    match:title = ^(github.com wants to open)$
    float = true
}

windowrule {
    name = brave-generic-popups
    match:class = ^(brave)$
    match:title = .*wants to open.*
    float = true
}

windowrule {
    name = browser-popups
    match:class = ^(brave|brave-browser|chromium|firefox)$
    match:title = .*wants to open.*
    float = true
}